# Site settings
title: Cagan Sit 
twitter_username: xaganic 
name: Cagan Sit 

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Hackerrank
   url: https://www.hackerrank.com/xaganic?hr_r=1
 - title: GitHub
   url: https://github.com/xaganic
 - title: StackOverflow
   url: http://stackoverflow.com/users/258813/rhinds

#Any buzzword skills you want to include
skills:
 - Nodejs (Express, Loopback)
 - Golang (mux)
 - PHP (Laravel)
 - Java (Spring, Spring Boot)
 - Javascript (React, jQuery)
 - HTML/CSS
 - MySql
 - NoSql (Redis, Mongodb)
 - Agile (Scrum, Kanban)
 - Jira
 - Software Methodologies
 - S.O.L.I.D
 - Microservices
 - API design
 - REST
 - Devops
 - Shell Script
 - Technical Architecture
 - Linux
 - Amazon Web Services
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Software Developer
   start: 2018
   end: 2019
   employer: Insider
   description: As soon as i finished my collage I started working on Insider. Mosty handled customer services. Mostly used Javascript to customise our partner's web site. Also I used PHP to connect our API's with their side.
 - title: Freelancer 
   start: 2017
   end: 2018
   employer: freelancer.com
   description: I always enjoyed dealing with computers. To finish my collage in time I had to quit my last job which is Nmobs/Genart Media. But i didn't stop. And tried to impore my self. And also built some personal websites.
 - title: Backend Developer 
   start: 2017
   end: 2018 
   employer: Nmobs/Genary Media
   description: My team mates and i were developed an API called Odin using Nodejs. And also developed a dashboard called "Tagon" using Reactjs.
 - title: PHP Developer
   start: 2016
   end: 2017
   employer: Monopol Tech
   description: I worked on Full Stack PHP Project while studying at the university.

#Education is required
education:
 - level: Bachelor of Computer Engineering
   date: 2018
   subject: Computer Engineering
   school: Istanbul Aydin University

#This section is optional (as is the image link below)
coursera:
   profileurl:
   courses:
    - title: Global Day of Code Retreat
      link: 
      optionalimage:
      date: 2014
    - title: GDG Devfest 2014
      link: 
      optionalimage:
      date: 2014
    - title: Python Meetup
      link: 
      optionalimage:
      date: 2016
    - title: GetHired Through Hire51's Data Analytics Hiring Drive
      link: 
      optionalimage:
      date: 2016
    - title: AR-GE Management Technology
      link: 
      optionalimage:
      date: 2016
    - title: BILTEG'16
      link: 
      optionalimage:
      date: 2016
    - title: Sony Cyber Security Workshop
      link: 
      optionalimage:
      date: 2017
    - title: Deep Web & Underground Security
      link: 
      optionalimage:
      date: 2017
    - title: Cezeri Cyber Security
      link: 
      optionalimage:
      date: 2017
    - title: Frontend Architect & Full Stack PHP Development
      link: 
      optionalimage:
      date: 2017
    - title: Basaksehir Living Lab Javascript Course
      link: 
      optionalimage:
      date: 2018

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - xaganic/dictionary-api
 - xaganic/zinger-api
 - xaganic/imdb-movie-finder
 - xaganic/creepy-bird
 - xaganic/GithubFinder
 - xaganic/Ehliyet_Sinavi_Uygulamasi

#Stackoverflow flair is optional
stackoverflow:
   profileurl:
   flairimageurl:

intro: |
  I am a software engineer with specialized Backend and Devops technologies. I have been working with API’s, automation tools and Backend Frameworks. The languages that I have experience most are Nodejs, PHP, Golang and Java. Also the Devops technologies I have been used: Jenkins, Travis, AWS (S3, Lambda, EC2, API Gateways, etc.). I have 2 years of experience with RESTFUL APIS and Database management systems.  Also I have 4 years experience Linux associative with Linux Management. Now I am focusing on Java Enterprise Edition technologies such as Spring, Spring Boot, Hibernate, Maven with Devops technologies. I have experience with Database Management Tools such as: SQL, SQLite for relational databases and  used Redis, MongoDB for non-relational databases.My goal is being a good developer <br/><br/>
  I enjoy building fully featured and qualified products, with a good Product Management focus and a good emphasis on good engineering principles and clean code. It is really important to care about writing clean codes to make qualified softwares. I have one year experience with code review and tried to apply code review standards on company. I have good knowledge about programming paradigms  such as Imperative, Declerative, Structured, Object Oriented, Functional, Event Driven, Procedural. Always try to implement my project using most proper paradigms. It is so important to know Data Structures and using SOLID principles to create good software. Also design patterns I always care about Singleton, Prototype (in javascript), Observer, Factory to build qualified softwares.<br/><br/>
  I always enjoyed deal with softwares in my life. I want to build qualified and scalable projects using new and reliable technologies. I like to write Medium articles, Solve Hackerrank problems, and open source in my spare time.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo:
   <strong>Java</strong>: Mostly used for Data structures and Design of Algorithms. I also made several games when i was in university. Recently i am improving my knowledge of Java EE (Spring Framework, Hibernates, etc.)<br/><br/>
   <strong>Nodejs</strong>: My most experienced technology is Nodejs. When i was intern a campany I took a role as backend developer. My team mates and i developed a big API using OPEN API standarts. Also i have used several Nodejs frameworks like Adonisjs, Loopback, Socket.io, etc. In my collage I have made my thesis using Nodejs<br/><br/>
   <strong>GO</strong>: When i was working on Insider. There were several problems with automation. And I decided to make our people life easier. And I need to write a Food Bot for the peoeple. And i learned Go language to make the response times much more shorter. And then i realized i liked Go so much. And i continued to use Golang for my personal projects.(Web Projects, Microservices)<br/><br/>
   <strong>Devops</strong>: In university i was started to use Linux. And i really enjoyed it. Because it seemed like it is a Virtual World. So keept using Linux. And do some devops stuffs. Then started to using Devops and automation stuffs. The last company that i was workign on was using AWS cloud. I tried to make experience using Jenkins, Docker, AWS, Shell Script, etc. And they gave me a permission to be able to do that.<br/><br/>
   <strong>PHP</strong>: The first backend language that i learned is PHP. When i was doing my first internship We needed to make a website using PHP. And we used a framework called Codeigniter. Then i liked PHP and learned a new framework called Laravel. I have made several websites using PHP for my Freelance works.<br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using EC2. I have also experience lambda functions and S3.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management tools like Git, Maven, Jenkins, etc. I have experience with an array of testing tools and technologies.<br/><br/>